// <auto-generated />
using System;
using AnbarUchotu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnbarUchotu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200723193833_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("AnbarUchotu.Models.Mal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirEdedinQiymeti")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Istehsal")
                        .HasColumnType("TEXT");

                    b.Property<string>("MalAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Miqdar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qablasma")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonIstifade")
                        .HasColumnType("TEXT");

                    b.Property<int>("YekunQiymet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirEdedinQiymeti = 150,
                            Istehsal = new DateTime(2020, 7, 23, 23, 38, 33, 668, DateTimeKind.Local).AddTicks(5479),
                            MalAdi = "test mal",
                            Miqdar = 2,
                            Qablasma = "100 ml",
                            SonIstifade = new DateTime(2021, 1, 23, 23, 38, 33, 669, DateTimeKind.Local).AddTicks(8142),
                            YekunQiymet = 300
                        },
                        new
                        {
                            Id = 2,
                            BirEdedinQiymeti = 12,
                            Istehsal = new DateTime(2020, 7, 23, 23, 38, 33, 669, DateTimeKind.Local).AddTicks(9771),
                            MalAdi = "test mal 2",
                            Miqdar = 4,
                            Qablasma = "50 ml",
                            SonIstifade = new DateTime(2021, 1, 23, 23, 38, 33, 669, DateTimeKind.Local).AddTicks(9786),
                            YekunQiymet = 48
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
